### ISSUE TITLE
Cross build for latest Scala/sbt

### ISSUE THREAD

**Issue by dkichler** [reugn/dynamic#3]
Would be great to compile this to Scala 2.13 as well.  

Howver, I think any new updates will be complicated by the fact that Bintray has been shutdown.  Any interest in reviving this project and possibly a new publishing mechanism?  I could probably lend a hand if the author is supportive.

**Comment by reugn** [comment]
@dkichler, thanks for your interest in `Dynamic`. I have revived the project and added Scala 2.13 support. I also plan to publish it to Maven Central (most likely) instead of Bintray, which has stopped its service recently, as you mentioned.

**Comment by dkichler** [comment]
Awesome - thanks for the quick response @reugn, I look forward to the next version from Maven Central (or otherwise)!

**Comment by reugn** [comment]
v0.2.0 released.

**Comment by dkichler** [comment]
Excellent!  Thanks so much for the quick release and the new version @reugn 🎉
